2021-08-26 16:31:06,238 INFO    MainThread:9908 [wandb_setup.py:_flush():69] setting env: {}
2021-08-26 16:31:06,239 INFO    MainThread:9908 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-26 16:31:06,239 INFO    MainThread:9908 [wandb_init.py:_log_setup():342] Logging user logs to /opt/ml/git/JH/ByeBye/wandb/run-20210826_163106-31q7velt/logs/debug.log
2021-08-26 16:31:06,239 INFO    MainThread:9908 [wandb_init.py:_log_setup():343] Logging internal logs to /opt/ml/git/JH/ByeBye/wandb/run-20210826_163106-31q7velt/logs/debug-internal.log
2021-08-26 16:31:06,239 INFO    MainThread:9908 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f5d803a9c10>
2021-08-26 16:31:06,240 INFO    MainThread:9908 [wandb_init.py:init():375] calling init triggers
2021-08-26 16:31:06,240 INFO    MainThread:9908 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {'lr': 0.00018, 'dropout': 0.5, 'architecture': 'efficientnet-b6 + 3way', 'dataset': 'vanilla + mask', 'augmentation': 'None', 'age_weightedloss': [1.0, 1.0, 3.0], 'gender_weightedloss': [1.5, 1.0], 'gamma': 0.8, 'batch_size': 32, 'epochs': 15, 'model': 'efficientnet-b6'}
2021-08-26 16:31:06,240 INFO    MainThread:9908 [wandb_init.py:init():424] starting backend
2021-08-26 16:31:06,240 INFO    MainThread:9908 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-08-26 16:31:06,264 INFO    MainThread:9908 [backend.py:ensure_launched():135] starting backend process...
2021-08-26 16:31:06,272 INFO    MainThread:9908 [backend.py:ensure_launched():139] started backend process with pid: 9959
2021-08-26 16:31:06,273 INFO    MainThread:9908 [wandb_init.py:init():429] backend started and connected
2021-08-26 16:31:06,291 INFO    MainThread:9908 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-26 16:31:06,292 INFO    MainThread:9908 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-08-26 16:31:06,292 INFO    MainThread:9908 [wandb_init.py:init():477] updated telemetry
2021-08-26 16:31:06,292 INFO    MainThread:9908 [wandb_init.py:init():500] communicating current version
2021-08-26 16:31:07,046 INFO    MainThread:9908 [wandb_init.py:init():505] got version response 
2021-08-26 16:31:07,046 INFO    MainThread:9908 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-26 16:31:07,396 INFO    MainThread:9908 [wandb_init.py:init():540] starting run threads in backend
2021-08-26 16:31:09,197 WARNING MainThread:9908 [wandb_init.py:init():795] interrupted
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 775, in init
    run = wi.init()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 543, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 801, in communicate_run_start
    result = self._communicate(rec)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 539, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 77, in get
    is_set = self._object_ready.wait(timeout)
  File "/opt/conda/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/conda/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
